# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef45ab6e13fe83b5d16ec13fe1ae0cef6377c5bfbc0c98df68f7704e320886f5b9dd84f1718b48c9a03292408d4dc6436b0784986f50e683256a9216cb33b96

test:
  secret_key_base: 6df38b26284fcf7e485b35b613d16df0ee76cfa2f47c99106542077adf7505eb4679fcae8ea3580de981b6a8862b346bbc76e677ac73b8e58d7656912f14a4a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
